remote_theme : jekyll/minima
url : "https://sonjoosik.github.io"
baseurl : ""
theme: minima

title: Son Joo Sik
author: sonjoosik
email: sonjoosik@gmail.com
description: > 
  

github_username:  sonjoosik
linkedin_username: sonjoosik

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

header_pages:
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
