remote_theme : jekyll/minima
url : "https://sonjoosik.com"
baseurl : ""
theme: minima

title: Hello, world!
author: sonjoosik
email: sonjoosik@gmail.com
description: > 
  

github_username:  sonjoosik
linkedin_username: sonjoosik

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - a
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
