remote_theme: jekyll/minima
url: "https://sonjoosik.com"
baseurl: ""
theme: minima

title: Son, Joo Sik (손주식)
author: sonjoosik
email: sonjoosik@gmail.com
  
facebook_username: sonjoosik
linkedin_username: sonjoosik

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - a

google_analytics_id: UA-69012576-1

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
