remote_theme : jekyll/minima
url : "https://sonjoosik.github.io"
baseurl : ""

title: Son Joo Sik
author: sonjoosik
email: sonjoosik@gmail.com
description: > 
  

github_username:  sonjoosik
linkedin_username: sonjoosik

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
