remote_theme : jekyll/minima
url : "https://sonjoosik.com"
baseurl : ""
theme: minima

title: Hello, world!
author: sonjoosik
email: sonjoosik@gmail.com
description: >
  My name is Joosik Son. I am a site reliability engineer and researcher at NAVER SEARCH.
  
facebook_username: sonjoosik
linkedin_username: sonjoosik

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - a

google_analytics_id: UA-69012576-1

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
